eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name:  trend-trading-backtest-service

feign.hystrix.enabled: true
zipkin:
  base-url: http://localhost:9411