spring:
  application:
    name: index-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/heatsmile/trendConfig
          search-paths: respo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
